general {
    before_sleep_cmd = hyprlock
    lock_cmd = hyprlock
    ignore_dbus_inhibit = false
}

listener {
    lid_close_cmd = hyprlock
    lid_open_cmd = 
}

timeout {
    timeout = 300
    cmd = hyprlock
}
